server:
  port: 8090

spring:
  application:
    name: Cards-MS
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true

logging:
  level:
    root: info
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: env, beans